
MAKE = make

.PHONY: all
all:
	$(MAKE) -j 1 -C OBJ/K210_GCC/DEMO all

.PHONY: clean
clean:
	$(MAKE) -j 1 -C OBJ/K210_GCC/DEMO clean

.PHONY: realclean
realclean:
	$(MAKE) -j 1 -C OBJ/K210_GCC/DEMO realclean
